sudo: false
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
  - npm run build
script:
  - npm run test
after_success:
  - npm run report-coverage
  - npm run semantic-release